# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18b52ef0356fc59a7d797c5263e4ad6c2fc5d9c3e41c822ba9d54ec1a5988d166690ec3b31900b268a911f07bc2565458fea3a0d075556d576a74c2788225520

test:
  secret_key_base: d84988fe9fb056dbd097c6ce49b40ff5bda88c6452f4089c25377a3c12b21172cc4eb3a15ca9d1b82f1556ddab043fbc10af585f38503924927892655e5af0ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
